# gsl configuration

# GSL_HAVE_C99_INLINE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_C99_INLINE.cmake)
if (NOT GSL_HAVE_C99_INLINE)
    set(GSL_HAVE_C99_INLINE 0)
endif ()

# GSL_HAVE_DECL_ACOSH
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_ACOSH.cmake)
if (NOT GSL_HAVE_DECL_ACOSH)
    set(GSL_HAVE_DECL_ACOSH 0)
endif ()

# GSL_HAVE_DECL_ASINH
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_ASINH.cmake)
if (NOT GSL_HAVE_DECL_ASINH)
    set(GSL_HAVE_DECL_ASINH 0)
endif ()

# GSL_HAVE_DECL_ATANH
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_ATANH.cmake)
if (NOT GSL_HAVE_DECL_ATANH)
    set(GSL_HAVE_DECL_ATANH 0)
endif ()

# GSL_HAVE_DECL_EXPM1
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_EXPM1.cmake)
if (NOT GSL_HAVE_DECL_EXPM1)
    set(GSL_HAVE_DECL_EXPM1 0)
endif ()

# GSL_HAVE_DECL_FEENABLEEXCEPT
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_FEENABLEEXCEPT.cmake)
if (NOT GSL_HAVE_DECL_FEENABLEEXCEPT)
    set(GSL_HAVE_DECL_FEENABLEEXCEPT 0)
endif ()

# GSL_HAVE_DECL_FESETTRAPENABLE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_FESETTRAPENABLE.cmake)
if (NOT GSL_HAVE_DECL_FESETTRAPENABLE)
    set(GSL_HAVE_DECL_FESETTRAPENABLE 0)
endif ()

# GSL_HAVE_DECL_FINITE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_FINITE.cmake)
if (NOT GSL_HAVE_DECL_FINITE)
    set(GSL_HAVE_DECL_FINITE 0)
endif ()

# GSL_HAVE_DECL_FPRND_T
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_FPRND_T.cmake)
if (NOT GSL_HAVE_DECL_FPRND_T)
    set(GSL_HAVE_DECL_FPRND_T 0)
endif ()

# GSL_HAVE_DECL_FREXP
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_FREXP.cmake)
if (NOT GSL_HAVE_DECL_FREXP)
    set(GSL_HAVE_DECL_FREXP 0)
endif ()

# GSL_HAVE_DECL_HYPOT
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_HYPOT.cmake)
if (NOT GSL_HAVE_DECL_HYPOT)
    set(GSL_HAVE_DECL_HYPOT 0)
endif ()

# GSL_HAVE_DECL_ISFINITE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_ISFINITE.cmake)
if (NOT GSL_HAVE_DECL_ISFINITE)
    set(GSL_HAVE_DECL_ISFINITE 0)
endif ()

# GSL_HAVE_DECL_ISINF
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_ISINF.cmake)
if (NOT GSL_HAVE_DECL_ISINF)
    set(GSL_HAVE_DECL_ISINF 0)
endif ()

# GSL_HAVE_DECL_ISNAN
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_ISNAN.cmake)
if (NOT GSL_HAVE_DECL_ISNAN)
    set(GSL_HAVE_DECL_ISNAN 0)
endif ()

# GSL_HAVE_DECL_LDEXP
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_LDEXP.cmake)
if (NOT GSL_HAVE_DECL_LDEXP)
    set(GSL_HAVE_DECL_LDEXP 0)
endif ()

# GSL_HAVE_DECL_LOG1P
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DECL_LOG1P.cmake)
if (NOT GSL_HAVE_DECL_LOG1P)
    set(GSL_HAVE_DECL_LOG1P 0)
endif ()

# GSL_HAVE_DLFCN_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DLFCN_H.cmake)
if (NOT GSL_HAVE_DLFCN_H)
    set(GSL_HAVE_DLFCN_H 0)
endif ()

# GSL_HAVE_DOPRNT
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DOPRNT.cmake)
if (NOT GSL_HAVE_DOPRNT)
    set(GSL_HAVE_DOPRNT 0)
endif ()

# GSL_HAVE_EXIT_SUCCESS_AND_FAILURE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_EXIT_SUCCESS_AND_FAILURE.cmake)
if (NOT GSL_HAVE_EXIT_SUCCESS_AND_FAILURE)
    set(GSL_HAVE_EXIT_SUCCESS_AND_FAILURE 0)
endif ()

# GSL_HAVE_EXTENDED_PRECISION_REGISTERS
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_EXTENDED_PRECISION_REGISTERS.cmake)
if (NOT GSL_HAVE_EXTENDED_PRECISION_REGISTERS)
    set(GSL_HAVE_EXTENDED_PRECISION_REGISTERS 0)
endif ()

# GSL_HAVE_FPU_X86_SSE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_FPU_X86_SSE.cmake)
if (NOT GSL_HAVE_FPU_X86_SSE)
    set(GSL_HAVE_FPU_X86_SSE 0)
endif ()

# GSL_HAVE_IEEEFP_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_IEEEFP_H.cmake)
if (NOT GSL_HAVE_IEEEFP_H)
    set(GSL_HAVE_IEEEFP_H 0)
endif ()

# GSL_HAVE_IEEE_COMPARISONS
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_IEEE_COMPARISONS.cmake)
if (NOT GSL_HAVE_IEEE_COMPARISONS)
    set(GSL_HAVE_IEEE_COMPARISONS 0)
endif ()

# GSL_HAVE_IEEE_DENORMALS
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_IEEE_DENORMALS.cmake)
if (NOT GSL_HAVE_IEEE_DENORMALS)
    set(GSL_HAVE_IEEE_DENORMALS 0)
endif ()

# GSL_HAVE_INLINE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_INLINE.cmake)
if (NOT GSL_HAVE_INLINE)
    set(GSL_HAVE_INLINE 0)
endif ()

# GSL_HAVE_INTTYPES_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_INTTYPES_H.cmake)
if (NOT GSL_HAVE_INTTYPES_H)
    set(GSL_HAVE_INTTYPES_H 0)
endif ()

# GSL_HAVE_LIBM
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_LIBM.cmake)
if (NOT GSL_HAVE_LIBM)
    set(GSL_HAVE_LIBM 0)
endif ()

# GSL_HAVE_MEMCPY
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_MEMCPY.cmake)
if (NOT GSL_HAVE_MEMCPY)
    set(GSL_HAVE_MEMCPY 0)
endif ()

# GSL_HAVE_MEMMOVE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_MEMMOVE.cmake)
if (NOT GSL_HAVE_MEMMOVE)
    set(GSL_HAVE_MEMMOVE 0)
endif ()

# GSL_HAVE_MEMORY_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_MEMORY_H.cmake)
if (NOT GSL_HAVE_MEMORY_H)
    set(GSL_HAVE_MEMORY_H 0)
endif ()

# GSL_HAVE_PRINTF_LONGDOUBLE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_PRINTF_LONGDOUBLE.cmake)
if (NOT GSL_HAVE_PRINTF_LONGDOUBLE)
    set(GSL_HAVE_PRINTF_LONGDOUBLE 0)
endif ()

# GSL_HAVE_STDINT_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STDINT_H.cmake)
if (NOT GSL_HAVE_STDINT_H)
    set(GSL_HAVE_STDINT_H 0)
endif ()

# GSL_HAVE_STDLIB_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STDLIB_H.cmake)
if (NOT GSL_HAVE_STDLIB_H)
    set(GSL_HAVE_STDLIB_H 0)
endif ()

# GSL_HAVE_STRDUP
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STRDUP.cmake)
if (NOT GSL_HAVE_STRDUP)
    set(GSL_HAVE_STRDUP 0)
endif ()

# GSL_HAVE_STRINGS_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STRINGS_H.cmake)
if (NOT GSL_HAVE_STRINGS_H)
    set(GSL_HAVE_STRINGS_H 0)
endif ()

# GSL_HAVE_STRING_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STRING_H.cmake)
if (NOT GSL_HAVE_STRING_H)
    set(GSL_HAVE_STRING_H 0)
endif ()

# GSL_HAVE_STRTOL
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STRTOL.cmake)
if (NOT GSL_HAVE_STRTOL)
    set(GSL_HAVE_STRTOL 0)
endif ()

# GSL_HAVE_STRTOUL
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_STRTOUL.cmake)
if (NOT GSL_HAVE_STRTOUL)
    set(GSL_HAVE_STRTOUL 0)
endif ()

# GSL_HAVE_SYS_STAT_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_SYS_STAT_H.cmake)
if (NOT GSL_HAVE_SYS_STAT_H)
    set(GSL_HAVE_SYS_STAT_H 0)
endif ()

# GSL_HAVE_SYS_TYPES_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_SYS_TYPES_H.cmake)
if (NOT GSL_HAVE_SYS_TYPES_H)
    set(GSL_HAVE_SYS_TYPES_H 0)
endif ()

# GSL_HAVE_UNISTD_H
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_UNISTD_H.cmake)
if (NOT GSL_HAVE_UNISTD_H)
    set(GSL_HAVE_UNISTD_H 0)
endif ()

# GSL_HAVE_VPRINTF
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_VPRINTF.cmake)
if (NOT GSL_HAVE_VPRINTF)
    set(GSL_HAVE_VPRINTF 0)
endif ()

# GSL_HAVE_GNUSPARC_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_GNUSPARC_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_GNUSPARC_IEEE_INTERFACE)
    set(GSL_HAVE_GNUSPARC_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_GNUM68K_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_GNUM68K_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_GNUM68K_IEEE_INTERFACE)
    set(GSL_HAVE_GNUM68K_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_GNUPPC_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_GNUPPC_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_GNUPPC_IEEE_INTERFACE)
    set(GSL_HAVE_GNUPPC_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_GNUX86_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_GNUX86_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_GNUX86_IEEE_INTERFACE)
    set(GSL_HAVE_GNUX86_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_SUNOS4_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_SUNOS4_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_SUNOS4_IEEE_INTERFACE)
    set(GSL_HAVE_SUNOS4_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_SOLARIS_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_SOLARIS_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_SOLARIS_IEEE_INTERFACE)
    set(GSL_HAVE_SOLARIS_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_HPUX11_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_HPUX11_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_HPUX11_IEEE_INTERFACE)
    set(GSL_HAVE_HPUX11_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_HPUX_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_HPUX_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_HPUX_IEEE_INTERFACE)
    set(GSL_HAVE_HPUX_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_TRU64_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_TRU64_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_TRU64_IEEE_INTERFACE)
    set(GSL_HAVE_TRU64_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_IRIX_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_IRIX_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_IRIX_IEEE_INTERFACE)
    set(GSL_HAVE_IRIX_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_AIX_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_AIX_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_AIX_IEEE_INTERFACE)
    set(GSL_HAVE_AIX_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_FREEBSD_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_FREEBSD_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_FREEBSD_IEEE_INTERFACE)
    set(GSL_HAVE_FREEBSD_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_OS2EMX_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_OS2EMX_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_OS2EMX_IEEE_INTERFACE)
    set(GSL_HAVE_OS2EMX_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_NETBSD_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_NETBSD_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_NETBSD_IEEE_INTERFACE)
    set(GSL_HAVE_NETBSD_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_OPENBSD_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_OPENBSD_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_OPENBSD_IEEE_INTERFACE)
    set(GSL_HAVE_OPENBSD_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_DARWIN_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DARWIN_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_DARWIN_IEEE_INTERFACE)
    set(GSL_HAVE_DARWIN_IEEE_INTERFACE 0)
endif ()

# GSL_HAVE_DARWIN86_IEEE_INTERFACE
include(${SOURCE_DIR}/cmake/config/GSL_HAVE_DARWIN86_IEEE_INTERFACE.cmake)
if (NOT GSL_HAVE_DARWIN86_IEEE_INTERFACE)
    set(GSL_HAVE_DARWIN86_IEEE_INTERFACE 0)
endif ()

# GSL_STDC_HEADERS
include(${SOURCE_DIR}/cmake/config/GSL_STDC_HEADERS.cmake)
if (NOT GSL_STDC_HEADERS)
    set(GSL_STDC_HEADERS 0)
endif ()

