# gsl configuration
# GSL_HAVE_C99_INLINE
set(GSL_HAVE_C99_INLINE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_C99_INLINE.cmake)

# GSL_HAVE_DECL_ACOSH
set(GSL_HAVE_DECL_ACOSH 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_ACOSH.cmake)

# GSL_HAVE_DECL_ASINH
set(GSL_HAVE_DECL_ASINH 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_ASINH.cmake)

# GSL_HAVE_DECL_ATANH
set(GSL_HAVE_DECL_ATANH 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_ATANH.cmake)

# GSL_HAVE_DECL_EXPM1
set(GSL_HAVE_DECL_EXPM1 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_EXPM1.cmake)

# GSL_HAVE_DECL_FEENABLEEXCEPT
set(GSL_HAVE_DECL_FEENABLEEXCEPT 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_FEENABLEEXCEPT.cmake)

# GSL_HAVE_DECL_FESETTRAPENABLE
set(GSL_HAVE_DECL_FESETTRAPENABLE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_FESETTRAPENABLE.cmake)

# GSL_HAVE_DECL_FINITE
set(GSL_HAVE_DECL_FINITE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_FINITE.cmake)

# GSL_HAVE_DECL_FPRND_T
set(GSL_HAVE_DECL_FPRND_T 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_FPRND_T.cmake)

# GSL_HAVE_DECL_FREXP
set(GSL_HAVE_DECL_FREXP 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_FREXP.cmake)

# GSL_HAVE_DECL_HYPOT
set(GSL_HAVE_DECL_HYPOT 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_HYPOT.cmake)

# GSL_HAVE_DECL_ISFINITE
set(GSL_HAVE_DECL_ISFINITE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_ISFINITE.cmake)

# GSL_HAVE_DECL_ISINF
set(GSL_HAVE_DECL_ISINF 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_ISINF.cmake)

# GSL_HAVE_DECL_ISNAN
set(GSL_HAVE_DECL_ISNAN 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_ISNAN.cmake)

# GSL_HAVE_DECL_LDEXP
set(GSL_HAVE_DECL_LDEXP 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_LDEXP.cmake)

# GSL_HAVE_DECL_LOG1P
set(GSL_HAVE_DECL_LOG1P 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DECL_LOG1P.cmake)

# GSL_HAVE_DLFCN_H
set(GSL_HAVE_DLFCN_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DLFCN_H.cmake)

# GSL_HAVE_DOPRNT
set(GSL_HAVE_DOPRNT 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DOPRNT.cmake)

# GSL_HAVE_EXIT_SUCCESS_AND_FAILURE
set(GSL_HAVE_EXIT_SUCCESS_AND_FAILURE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_EXIT_SUCCESS_AND_FAILURE.cmake)

# GSL_HAVE_EXTENDED_PRECISION_REGISTERS
set(GSL_HAVE_EXTENDED_PRECISION_REGISTERS 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_EXTENDED_PRECISION_REGISTERS.cmake)

# GSL_HAVE_FPU_X86_SSE
set(GSL_HAVE_FPU_X86_SSE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_FPU_X86_SSE.cmake)

# GSL_HAVE_IEEEFP_H
set(GSL_HAVE_IEEEFP_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_IEEEFP_H.cmake)

# GSL_HAVE_IEEE_COMPARISONS
set(GSL_HAVE_IEEE_COMPARISONS 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_IEEE_COMPARISONS.cmake)

# GSL_HAVE_IEEE_DENORMALS
set(GSL_HAVE_IEEE_DENORMALS 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_IEEE_DENORMALS.cmake)

# GSL_HAVE_INLINE
set(GSL_HAVE_INLINE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_INLINE.cmake)

# GSL_HAVE_INTTYPES_H
set(GSL_HAVE_INTTYPES_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_INTTYPES_H.cmake)

# GSL_HAVE_LIBM
set(GSL_HAVE_LIBM 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_LIBM.cmake)

# GSL_HAVE_MEMCPY
set(GSL_HAVE_MEMCPY 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_MEMCPY.cmake)

# GSL_HAVE_MEMMOVE
set(GSL_HAVE_MEMMOVE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_MEMMOVE.cmake)

# GSL_HAVE_MEMORY_H
set(GSL_HAVE_MEMORY_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_MEMORY_H.cmake)

# GSL_HAVE_PRINTF_LONGDOUBLE
set(GSL_HAVE_PRINTF_LONGDOUBLE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_PRINTF_LONGDOUBLE.cmake)

# GSL_HAVE_STDINT_H
set(GSL_HAVE_STDINT_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STDINT_H.cmake)

# GSL_HAVE_STDLIB_H
set(GSL_HAVE_STDLIB_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STDLIB_H.cmake)

# GSL_HAVE_STRDUP
set(GSL_HAVE_STRDUP 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STRDUP.cmake)

# GSL_HAVE_STRINGS_H
set(GSL_HAVE_STRINGS_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STRINGS_H.cmake)

# GSL_HAVE_STRING_H
set(GSL_HAVE_STRING_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STRING_H.cmake)

# GSL_HAVE_STRTOL
set(GSL_HAVE_STRTOL 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STRTOL.cmake)

# GSL_HAVE_STRTOUL
set(GSL_HAVE_STRTOUL 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_STRTOUL.cmake)

# GSL_HAVE_SYS_STAT_H
set(GSL_HAVE_SYS_STAT_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_SYS_STAT_H.cmake)

# GSL_HAVE_SYS_TYPES_H
set(GSL_HAVE_SYS_TYPES_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_SYS_TYPES_H.cmake)

# GSL_HAVE_UNISTD_H
set(GSL_HAVE_UNISTD_H 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_UNISTD_H.cmake)

# GSL_HAVE_VPRINTF
set(GSL_HAVE_VPRINTF 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_VPRINTF.cmake)

# GSL_HAVE_GNUSPARC_IEEE_INTERFACE
set(GSL_HAVE_GNUSPARC_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_GNUSPARC_IEEE_INTERFACE.cmake)

# GSL_HAVE_GNUM68K_IEEE_INTERFACE
set(GSL_HAVE_GNUM68K_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_GNUM68K_IEEE_INTERFACE.cmake)

# GSL_HAVE_GNUPPC_IEEE_INTERFACE
set(GSL_HAVE_GNUPPC_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_GNUPPC_IEEE_INTERFACE.cmake)

# GSL_HAVE_GNUX86_IEEE_INTERFACE
set(GSL_HAVE_GNUX86_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_GNUX86_IEEE_INTERFACE.cmake)

# GSL_HAVE_SUNOS4_IEEE_INTERFACE
set(GSL_HAVE_SUNOS4_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_SUNOS4_IEEE_INTERFACE.cmake)

# GSL_HAVE_SOLARIS_IEEE_INTERFACE
set(GSL_HAVE_SOLARIS_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_SOLARIS_IEEE_INTERFACE.cmake)

# GSL_HAVE_HPUX11_IEEE_INTERFACE
set(GSL_HAVE_HPUX11_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_HPUX11_IEEE_INTERFACE.cmake)

# GSL_HAVE_HPUX_IEEE_INTERFACE
set(GSL_HAVE_HPUX_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_HPUX_IEEE_INTERFACE.cmake)

# GSL_HAVE_TRU64_IEEE_INTERFACE
set(GSL_HAVE_TRU64_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_TRU64_IEEE_INTERFACE.cmake)

# GSL_HAVE_IRIX_IEEE_INTERFACE
set(GSL_HAVE_IRIX_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_IRIX_IEEE_INTERFACE.cmake)

# GSL_HAVE_AIX_IEEE_INTERFACE
set(GSL_HAVE_AIX_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_AIX_IEEE_INTERFACE.cmake)

# GSL_HAVE_FREEBSD_IEEE_INTERFACE
set(GSL_HAVE_FREEBSD_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_FREEBSD_IEEE_INTERFACE.cmake)

# GSL_HAVE_OS2EMX_IEEE_INTERFACE
set(GSL_HAVE_OS2EMX_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_OS2EMX_IEEE_INTERFACE.cmake)

# GSL_HAVE_NETBSD_IEEE_INTERFACE
set(GSL_HAVE_NETBSD_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_NETBSD_IEEE_INTERFACE.cmake)

# GSL_HAVE_OPENBSD_IEEE_INTERFACE
set(GSL_HAVE_OPENBSD_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_OPENBSD_IEEE_INTERFACE.cmake)

# GSL_HAVE_DARWIN_IEEE_INTERFACE
set(GSL_HAVE_DARWIN_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DARWIN_IEEE_INTERFACE.cmake)

# GSL_HAVE_DARWIN86_IEEE_INTERFACE
set(GSL_HAVE_DARWIN86_IEEE_INTERFACE 0)
include(${SOURCE_DIR}/cmake/have/GSL_HAVE_DARWIN86_IEEE_INTERFACE.cmake)

